name: deploy

on:
  push:
    branches:
      # Replace none with your desired branch (e.g. - main)
      - none


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run tests
        run: sudo apt-get update -y && sudo apt-get install python3.8 -y && sudo apt-get install python3-virtualenv -y && make test


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via scp
      uses: appleboy/scp-action@master
      with:
        # Add each of these fields as a Github "Secret"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        source: "./*"
        # Replace ./djengu with the name of your root directory
        target: "./djengu"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        # Replace ./djengu with the name of your root directory
        script:  cd djengu/ && make deploy

